### 1D array

In [9]:
import numpy as np

an_array = np.array([3, 33, 333]) 

print(type(an_array))             

<class 'numpy.ndarray'>


In [10]:
# because this is a 1-rank array, we need only one index to accesss each element
print(an_array[0], an_array[1], an_array[2]) 

3 33 333


In [11]:
an_array[0] =888            # ndarrays are mutable, here we change an element of the array

print(an_array)

[888  33 333]


## 2D Array

In [12]:
another = np.array([[11,12,13],[21,22,23]]) 
print(another) 



[[11 12 13]
 [21 22 23]]


## Accessing the elements

In [14]:
another[1,1]

22

### There are many way to create numpy arrays:


Here we create a number of different size arrays with different shapes and different pre-filled values.  numpy has a number of built in methods which help us quickly and easily create multidimensional arrays.

In [15]:
import numpy as np

# create a 2x2 array of zeros
ex1 = np.zeros((2,2))      
print(ex1)                              

[[0. 0.]
 [0. 0.]]


In [16]:
# create a 2x2 array filled with 9.0
ex2 = np.full((2,2), 9.0)  
print(ex2)   

[[9. 9.]
 [9. 9.]]


In [17]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex3 = np.eye(2,2)
print(ex3)  

[[1. 0.]
 [0. 1.]]


In [18]:
# create an array of ones
ex4 = np.ones((3,3))
print(ex4)    

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
print(ex5)    

[[0.41581602 0.39941775]
 [0.12457225 0.261963  ]]


### slicing:

In [57]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [58]:
a_slice = an_array[:2, 1:3]
print(a_slice)

[[12 13]
 [22 23]]


### selecting using row and column indices

In [64]:
# Create an array of indices
col_indices = np.array([0, 1, 2])
print('\nCol indices picked : ', col_indices)

row_indices = np.arange(3)
print('\nRows indices picked : ', row_indices)


Col indices picked :  [0 1 2]

Rows indices picked :  [0 1 2]


In [65]:
# Examine the pairings of row_indices and col_indices.  These are the elements we'll change next.
for row,col in zip(row_indices,col_indices):
    print(row, ", ",col)

0 ,  0
1 ,  1
2 ,  2


In [66]:
# Select one element from each row
print('Values in the array at those indices: ',an_array[row_indices,col_indices])

Values in the array at those indices:  [11 22 33]


### performing some action

In [67]:
# Change one element from each row using the indices selected
an_array[row_indices, col_indices] += 100000

print('\nChanged Array:')
print(an_array)


Changed Array:
[[100011   1000     13     14]
 [    21 100022     23     24]
 [    31     32 100033     34]]


### Filtering using a condition

In [60]:
# create a 3x2 array
an_array = np.array([[11,12], [21, 22], [31, 32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [61]:
# create a filter which will be boolean values for whether each element meets this condition
filter = (an_array > 15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [57]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

[21 22 31 32]


In [58]:
# For short, we could have just used the approach below without the need for the separate filter array.

an_array[an_array > 15]

array([21, 22, 31, 32])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter.  Let's add 100 to all the even values.

In [59]:
an_array[an_array % 2 == 0] +=100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


### change Datatypes:

In [33]:
ex3 = np.array([11.0, 21.0], dtype=np.int64) #You can also tell Python the  data type
print(ex3)

[11 21]


### Arithmetic Array Operations:

In [34]:
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


In [37]:
print(np.add(x, y))  
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))
print(np.sqrt(x))

[[322.1 324.1]
 [342.1 344.1]]
[[-100.1 -100.1]
 [-100.1 -100.1]]
[[23432.1 23755.2]
 [26753.1 27096.2]]
[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]
[[10.53565375 10.58300524]
 [11.         11.04536102]]


### Statistical Operations:

In [38]:
# setup a random 2 x 4 matrix
arr = 10 * np.random.randn(2,4)
print(arr)

[[  4.67219053 -21.42106009  -5.99085446  10.15766206]
 [ -1.50911347 -12.6150225    8.47654092   2.22830988]]


In [96]:
# compute the mean for all elements
print(arr.mean())

-2.4185483173261835


In [97]:
# compute the means by row
print(arr.mean(axis = 1))

[-3.67620079 -1.16089584]


In [98]:
# compute the means by column
print(arr.mean(axis = 0))

[  0.15172945   0.47290918 -10.20490597  -0.09392593]


In [99]:
# sum all the elements
print(arr.sum())

-19.348386538609468


In [100]:
# compute the medians
print(np.median(arr, axis = 1))

[-7.21553024 -1.31416388]


### Finding Unique elements:

In [48]:
array = np.array([1,2,1,4,2,1,4,2])

print(np.unique(array))

[1 2 4]


### Set Operations with np.array data type:

In [51]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [54]:
print( np.intersect1d(s1, s2) ) 

['bulb' 'chair']


In [107]:
print( np.union1d(s1, s2) )

['bulb' 'chair' 'desk' 'lamp']


In [111]:
print( np.setdiff1d(s1, s2) )# elements in s1 that are not in s2

['desk']


In [112]:
print( np.in1d(s1, s2) )#which element of s1 is also in s2

[False  True  True]


### Broadcasting:

In [75]:
import numpy as np

start = np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [76]:
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [77]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [74]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T

print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [117]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [118]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Reshaping array:

In [157]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [158]:
# reshape to be a 4 x 5 matrix
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### where condition

In [192]:
mat = np.random.rand(5,5)
mat

array([[0.07808834, 0.33028937, 0.80079523, 0.45117166, 0.62541003],
       [0.41499247, 0.02884736, 0.6201891 , 0.24243459, 0.73591452],
       [0.71548832, 0.11798716, 0.6247865 , 0.84074479, 0.27011644],
       [0.48855342, 0.87417338, 0.83446682, 0.18175405, 0.8333543 ],
       [0.07081142, 0.01027207, 0.02963625, 0.88517661, 0.08663208]])

In [193]:
np.where( mat > 0.5, 1000, -1)

array([[  -1,   -1, 1000,   -1, 1000],
       [  -1,   -1, 1000,   -1, 1000],
       [1000,   -1, 1000, 1000,   -1],
       [  -1, 1000, 1000,   -1, 1000],
       [  -1,   -1,   -1, 1000,   -1]])

### "any" or "all" conditionals

In [203]:
arr_bools = np.array([ True,False, True,False,True])

In [204]:
arr_bools.any()

#return true if any one is true

True

In [205]:
arr_bools.all()
#return true if all are true

False

### Random Number Generation:

In [69]:
Z = np.random.randint(low=2,high=50,size=(2,4))
print(Z)

[[33  8 30 43]
 [25 18 14 25]]


In [70]:
np.random.permutation(Z) #return a new ordering of elements in Z

array([[33,  8, 30, 43],
       [25, 18, 14, 25]])

### Merging Datasets

In [215]:
K = np.random.randint(low=2,high=50,size=(2,2))
print(K)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[12 23]
 [42 37]]

[[25 18]
 [ 8 25]]


In [216]:
np.vstack((K,M))

array([[12, 23],
       [42, 37],
       [25, 18],
       [ 8, 25]])

In [217]:
np.hstack((K,M))

array([[12, 23, 25, 18],
       [42, 37,  8, 25]])

In [218]:
np.concatenate([K, M], axis = 0)

array([[12, 23],
       [42, 37],
       [25, 18],
       [ 8, 25]])

In [176]:
np.concatenate([K, M.T], axis = 1)

array([[13, 19,  2, 23],
       [40,  8, 39, 47]])