## 1D Array

In [1]:
import numpy as np

an_array = np.array([3,33,333])

In [2]:
print(type(an_array))

<class 'numpy.ndarray'>


In [4]:
an_array[1]

33

In [5]:
an_array[0]=99
an_array

array([ 99,  33, 333])

### 2D array

In [7]:
another = np.array([[11,12,13],[21,22,23]])
print(another)

[[11 12 13]
 [21 22 23]]


In [10]:
another[0,2]

13

## Other ways to create numpy arrays

In [13]:
ex1 = np.zeros((3,3))
ex1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
ex = np.full((10,10),8)
ex

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8]])

In [18]:
ex2=np.eye(5,5)
ex2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
er=np.ones((5,5))
er

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
ran = np.random.random((4,4))
ran

array([[0.48141682, 0.09208188, 0.37550621, 0.05309748],
       [0.46696927, 0.09232355, 0.11540749, 0.34025868],
       [0.67737042, 0.89190784, 0.98940284, 0.43494019],
       [0.05608172, 0.58390479, 0.48070595, 0.11459102]])

### Slicing

In [27]:
arr = np.array([[1,2,3,4],[11,12,13,14],[21,22,23,24],[31,32,33,34]])
print(arr)

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [28]:
arr[:2,1:3]

array([[ 2,  3],
       [12, 13]])

In [31]:
row_indices = np.arange(3)
col_indices = np.arange(3)

In [33]:
for x,y in zip(row_indices,col_indices):
    print(x,',',y)

0 , 0
1 , 1
2 , 2


In [34]:
arr[row_indices,col_indices]

array([ 1, 12, 23])

In [35]:
arr[row_indices,col_indices]+=1000
arr

array([[1001,    2,    3,    4],
       [  11, 1012,   13,   14],
       [  21,   22, 1023,   24],
       [  31,   32,   33,   34]])

In [36]:
filter=arr>25
filter

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [ True,  True,  True,  True]])

In [37]:
arr[filter]

array([1001, 1012, 1023,   31,   32,   33,   34])

In [38]:
arr[arr>15]

array([1001, 1012,   21,   22, 1023,   24,   31,   32,   33,   34])

In [39]:
arr[arr%2==0]+=1000

In [40]:
arr

array([[1001, 1002,    3, 1004],
       [  11, 2012,   13, 1014],
       [  21, 1022, 1023, 1024],
       [  31, 1032,   33, 1034]])

### changing datatypes

In [42]:
ex = np.array([11.0,19.0,29.0],dtype=np.int64)
print(ex)

[11 19 29]


## Arithmetic Array operations

In [44]:
x = np.array([[1,2],[3,4]])
y=np.array([[2,2],[3,3]])

In [48]:
print(np.add(x,y))
print(np.subtract(x,y))

[[3 4]
 [6 7]]
[[-1  0]
 [ 0  1]]


## Statistical operations

In [51]:
arr = 100*np.random.randn(2,4)
arr

array([[-57.20413215, 140.47989808, -13.42323114, -46.73836858],
       [105.01723444,  52.20353283, 106.00830874, -46.22007964]])

In [52]:
arr.mean()

30.01539532474534

In [54]:
arr.mean(axis=1)

array([ 5.77854155, 54.2522491 ])

In [55]:
arr.sum()

240.12316259796273

In [56]:
array=np.array([1,2,1,2,11,2,3,3,3,4,5])
array

array([ 1,  2,  1,  2, 11,  2,  3,  3,  3,  4,  5])

In [57]:
np.unique(array)

array([ 1,  2,  3,  4,  5, 11])

## Set operations

In [58]:
s1 = np.array(['a','b','c'])
s2 = np.array(['d','b','c'])

In [61]:
print(np.intersect1d(s1,s2))

['b' 'c']


In [63]:
np.union1d(s1,s2)

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [65]:
np.setdiff1d(s1,s2)

array(['a'], dtype='<U1')

In [66]:
np.in1d(s1,s2)

array([False,  True,  True])